---
abstract: 'Wrap a WWW::Mechanize instance in an HTTP::Tiny compatible interface.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  HTTP::Response: '0'
  HTTP::Tiny: '0.022'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Tiny-Mech
provides:
  HTTP::Tiny::Mech:
    file: lib/HTTP/Tiny/Mech.pm
    version: '1.001002'
requires:
  HTTP::Request: '0'
  HTTP::Tiny: '0.022'
  WWW::Mechanize: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/HTTP-Tiny-Mech/issues
  homepage: https://github.com/kentnl/HTTP-Tiny-Mech
  repository: https://github.com/kentnl/HTTP-Tiny-Mech.git
version: '1.001002'
